# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# For x230t - GENERATE WITH: sudo nixos-generate-config --root / && mv /etc/nixos/hardware-configuration.nix hosts/x230t/

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/REPLACE_WITH_YOUR_UUID";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/REPLACE_WITH_YOUR_UUID";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Uncomment and modify to reflect your networking setup:
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
}
