# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# For x230t (Libreboot) - GENERATE WITH: sudo nixos-generate-config --root / && mv /etc/nixos/hardware-configuration.nix hosts/x230t/
# Partitionnement GPT requis :
#   1. Partition BIOS boot : 1 Mo, type ef02 (pas de filesystem, GRUB s'y installe)
#   2. Partition root : btrfs (ou ext4)
#   3. (optionnel) Partition swap

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/REPLACE_WITH_YOUR_UUID";
      fsType = "btrfs";
    };

  # Pas de /boot séparé avec GRUB BIOS - GRUB s'installe dans la partition BIOS boot (ef02)
  # Si tu veux un /boot séparé (ext4), décommente :
  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/REPLACE_WITH_YOUR_UUID";
  #     fsType = "ext4";
  #   };

  swapDevices = [ ];

  # Uncomment and modify to reflect your networking setup:
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
}
