# General Layout Configuration
# Hyprland - NixOS

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2

    # Couleurs bordures — variables définies dans colors.conf (généré par matugen)
    col.active_border = $active_border_color
    col.inactive_border = $inactive_border_color

    resize_on_border = true
    layout = dwindle
}
