general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 5 min — dim ecran
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# 8 min — verrouillage
listener {
    timeout = 480
    on-timeout = loginctl lock-session
}

# 10 min — DPMS off
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30 min — suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
