# Hyprlock — ecran de verrouillage
# Theme Catppuccin Mocha

general {
    hide_cursor = true
    grace = 3
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
}

# Heure
label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1.0)
    font_size = 90
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A %d %B"
    color = rgba(205, 214, 244, 0.8)
    font_size = 24
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}

# Champ mot de passe
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(245, 194, 231, 1.0)
    inner_color = rgba(30, 30, 46, 1.0)
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = true
    placeholder_text = <i>Mot de passe...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    check_color = rgba(166, 227, 161, 1.0)
    fail_color = rgba(243, 139, 168, 1.0)
    fail_text = <i>$FAIL</i>
}
