# Misc Configuration
# Hyprland - NixOS

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true

    # Empêche les apps de voler le focus (fix sélection texte Thunar/KiCad)
    focus_on_activate = false

    # VRR (Variable Refresh Rate) - désactivé par défaut
    vrr = 0
}
