# Window Rules
# Hyprland 0.53+ - NixOS Config

# === Portails XDG (file picker) ===
windowrule = float on, center on, size 900 600, match:class ^(xdg-desktop-portal)(.*)$

# === Apps systeme ===
windowrule = float on, size 800 600, center on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, center on, match:class ^(nm-connection-editor)$
windowrule = float on, center on, match:class ^(blueman-manager)$

# === Polkit (popup mot de passe) ===
windowrule = float on, center on, match:class ^(polkit-gnome-authentication-agent-1)$


# === KiCad ===
windowrule = center on, match:class ^(kicad)$

# === Utilitaires ===
windowrule = float on, match:class ^(file-roller)$
windowrule = float on, match:class ^(org.kde.partitionmanager)$
windowrule = float on, match:class ^(wdisplays)$
windowrule = float on, match:class ^(imv)$
windowrule = float on, match:class ^(mpv)$


# === Picture-in-Picture (Firefox/Chromium) ===
windowrule = float on, pin on, size 480 270, move 100%-490 100%-280, match:title ^(Picture-in-Picture)$

